### ISSUE TITLE
需要设置什么环境变量吗？

### ISSUE THREAD

**Issue by Dragon-Tab** [Pizz33/Qianji#1]
exec: "garble": executable file not found in %PATH%
![图片](https://github.com/Pizz33/Qianji/assets/53103912/f6e4f91b-bf2f-4e85-85e2-d7eaa232e868)

**Comment by Pizz33** [comment]
把 garble 添加至 环境变量 path 即可

**Comment by Dragon-Tab** [comment]
问题解决了 感谢
