### ISSUE TITLE
这是什么问题？没有反馈

### ISSUE THREAD

**Issue by xtclalala** [Pizz33/Qianji#16]
![屏幕截图 2023-12-05 111157](https://github.com/Pizz33/Qianji/assets/86792839/0831652a-eb55-4e1a-b562-a10ad4814549)

**Comment by xtclalala** [comment]
![Uploading 屏幕截图 2023-12-05 111157.png…]()

**Comment by xtclalala** [comment]
![屏幕截图 2023-12-05 111157](https://github.com/Pizz33/Qianji/assets/86792839/97af99e8-4ffc-4ae8-805c-b58f7a28eb36)

**Comment by Pizz33** [comment]
gcc看看装了没

**Comment by xtclalala** [comment]
![屏幕截图 2023-12-05 211346](https://github.com/Pizz33/Qianji/assets/86792839/83019798-aa2c-4bb5-a423-3170b63322b5)

**Comment by Pizz33** [comment]
用最新的试试 不清楚你这个原因

**Comment by xtclalala** [comment]
![屏幕截图 2023-12-06 145044](https://github.com/Pizz33/Qianji/assets/86792839/921fc155-3fa4-409f-bbe8-37a14f14c313)

**Comment by z0sen** [comment]
我也遇到了 最新版运行没反应
