### ISSUE TITLE
请问下问什么运行了Qianji_BypassAV.exe之后，只生成了build目录，没有exe文件

### ISSUE THREAD

**Issue by takuyasec** [Pizz33/Qianji#2]
![image](https://github.com/Pizz33/Qianji/assets/97492590/fe80d054-85c0-4f4a-b1e7-1f6d1e468322)

**Comment by Pizz33** [comment]
额 没碰到过这种情况 你要不换个环境再试一下？

**Comment by takuyasec** [comment]
> 额 没碰到过这种情况 你要不换个环境再试一下？

另外想请教下师傅，博客里面的免杀捆绑器应该如何安装和操作呢？方便讲下详细的步骤吗？

**Comment by Pizz33** [comment]
可以去参考一下渣渣师傅的gobinder 其实大体都差不多
