### ISSUE TITLE
双击运行后 没有任何反应

### ISSUE THREAD

**Issue by q3107771** [Pizz33/Qianji#3]
![QQ截图20230924004951](https://github.com/Pizz33/Qianji/assets/94402977/ce3b408e-4ffd-4a6c-b342-32ff65652d1c)
使用的cs4.0版本 
难道是cs版本过老的问题导致运行没任何反应吗

**Comment by q3107771** [comment]
解决了是我没下载相关garble等相关依赖

大哥刚才我测试  现在已经被360给查杀了

**Comment by Pizz33** [comment]
> 解决了是我没下载相关garble等相关依赖
> 
> 
> 
> 大哥刚才我测试  现在已经被360给查杀了

360查杀报qvm是资源问题 不是木马不免杀 你加个签名图标就过了

**Comment by q3107771** [comment]
> > 解决了我没有下载相关乱码等相关依赖
> > 大哥刚才我测试现在已经被360给查杀了
> 
> 360查杀报qvm是资源问题 不是木马不免杀你加个签名图标就过了

伪装签名不可以是吗？

**Comment by Pizz33** [comment]
> > > 解决了我没有下载相关乱码等相关依赖
> > > 大哥刚才我测试现在已经被360给查杀了
> > 
> > 
> > 360查杀报qvm是资源问题 不是木马不免杀你加个签名图标就过了
> 
> 伪装签名不可以是吗？

可以
