### ISSUE TITLE
两个go的包已经不在了

### ISSUE THREAD

**Issue by Bness-y** [Pizz33/Qianji#4]
![图片](https://github.com/Pizz33/Qianji/assets/71207047/5431a2ce-2233-49d9-820f-a63366f90f79)
![图片](https://github.com/Pizz33/Qianji/assets/71207047/560d1f3c-ec46-437d-b5b2-9f2652c45268)
![图片](https://github.com/Pizz33/Qianji/assets/71207047/c1f58000-7785-4c0c-9bfd-a1185862c7b1)

**Comment by Pizz33** [comment]
> ![图片](https://github.com/Pizz33/Qianji/assets/71207047/5431a2ce-2233-49d9-820f-a63366f90f79)
> 
> ![图片](https://github.com/Pizz33/Qianji/assets/71207047/560d1f3c-ec46-437d-b5b2-9f2652c45268)
> 
> ![图片](https://github.com/Pizz33/Qianji/assets/71207047/c1f58000-7785-4c0c-9bfd-a1185862c7b1)
> 
> 

仔细按照步骤命令按照依赖
