### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by bmzz2233** [Pizz33/Qianji#6]
安装依赖后，还是出现该错误（未安装git）
![image](https://github.com/Pizz33/Qianji/assets/129285186/88a788ed-0603-47ab-9b31-59832ce3e853)
![image](https://github.com/Pizz33/Qianji/assets/129285186/5a2218ee-5272-4b8d-98f0-286f0b2407c1)

**Comment by Pizz33** [comment]
好好看readme的命令对着一步步敲 少了go mod init 1

**Comment by bmzz2233** [comment]
> 好好看readme的命令对着一步步敲 少了go mod init 1

这个已经试过了，，这是我敲的第二遍，所以截图没截到
![image](https://github.com/Pizz33/Qianji/assets/129285186/11762788-afb5-49e3-8735-d5e3c57e809d)
